// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

let testFixturesDir = "./src/__tests__/fixtures";

let testOutputDir = "./src/__tests__/output";

function createMockPropUsage(propName, componentName, line, column, value, isSpread, type_) {
  return {
    propName: propName,
    componentName: componentName,
    line: line,
    column: column,
    value: value,
    isSpread: isSpread,
    type_: type_
  };
}

function createMockComponentAnalysis(componentName, file, props, propsInterface) {
  return {
    componentName: componentName,
    file: file,
    props: props,
    propsInterface: propsInterface
  };
}

function createMockAnalysisSummary(totalFiles, totalComponents, totalProps) {
  return {
    totalFiles: totalFiles,
    totalComponents: totalComponents,
    totalProps: totalProps
  };
}

function readTestFile(filename) {
  let filePath = Nodepath.join([
    testFixturesDir,
    filename
  ]);
  try {
    return Nodefs.readFileSync(filePath, "utf-8");
  } catch (exn) {
    return "";
  }
}

function writeTestOutput(filename, content) {
  let filePath = Nodepath.join([
    testOutputDir,
    filename
  ]);
  try {
    Nodefs.writeFileSync(filePath, content);
    return;
  } catch (exn) {
    return;
  }
}

function assertFileExists(path) {
  return Nodefs.existsSync(path);
}

function assertFileIsValid(path) {
  if (!Nodefs.existsSync(path)) {
    return false;
  }
  let stats = Nodefs.statSync(path);
  return stats.isFile();
}

function benchmark(operationName, fn) {
  let startTime = Date.now();
  fn();
  let endTime = Date.now();
  let duration = endTime - startTime;
  return {
    operation: operationName,
    duration: duration,
    memoryUsage: 0
  };
}

let sampleJSXContent = `
import React from 'react';

interface ButtonProps {
  onClick: () => void;
  children: React.ReactNode;
  disabled?: boolean;
}

const Button: React.FC<ButtonProps> = ({ onClick, children, disabled }) => {
  return (
    <button onClick={onClick} disabled={disabled}>
      {children}
    </button>
  );
};

export default Button;
`;

let sampleUsageContent = `
import React from 'react';
import { Button } from './Button';

const App = () => {
  return (
    <div>
      <Button onClick={() => console.log('clicked')}>
        Click me
      </Button>
      <Button onClick={() => console.log('disabled')} disabled={true}>
        Disabled button
      </Button>
    </div>
  );
};

export default App;
`;

export {
  testFixturesDir,
  testOutputDir,
  createMockPropUsage,
  createMockComponentAnalysis,
  createMockAnalysisSummary,
  readTestFile,
  writeTestOutput,
  assertFileExists,
  assertFileIsValid,
  benchmark,
  sampleJSXContent,
  sampleUsageContent,
}
/* node:fs Not a pure module */
