// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

async function glob(pattern, _options) {
  if (pattern === "**/*.{js,jsx,ts,tsx}") {
    return Promise.resolve([]);
  } else {
    return Promise.resolve([]);
  }
}

function consoleLog(message) {
  console.log(message);
}

function consoleError(message) {
  console.error(message);
}

function isSupportedFileExtension(filename) {
  let ext = Nodepath.extname(filename);
  if (ext === ".js" || ext === ".jsx" || ext === ".ts") {
    return true;
  } else {
    return ext === ".tsx";
  }
}

function isFile(path) {
  try {
    let stats = Nodefs.statSync(path);
    return stats.isFile();
  } catch (exn) {
    return false;
  }
}

function isDirectory(path) {
  try {
    let stats = Nodefs.statSync(path);
    return stats.isDirectory();
  } catch (exn) {
    return false;
  }
}

function fileExists(path) {
  return Nodefs.existsSync(path);
}

export {
  glob,
  consoleLog,
  consoleError,
  isSupportedFileExtension,
  isFile,
  isDirectory,
  fileExists,
}
/* node:fs Not a pure module */
