// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zod from "zod";
import Zod$1 from "zod";
import * as McpJs from "@modelcontextprotocol/sdk/server/mcp.js";
import * as StdioJs from "@modelcontextprotocol/sdk/server/stdio.js";

function createServer(name, version) {
  return McpJs.McpServer({
              name: name,
              version: version
            });
}

function createTransport() {
  return StdioJs.StdioServerTransport();
}

function createStringSchema() {
  return Zod.string();
}

function createBooleanSchema() {
  return Zod.boolean();
}

function createNumberSchema() {
  return Zod.number();
}

function createOptionalSchema(schema) {
  return Zod.optional(schema);
}

function createDefaultSchema(schema, defaultValue) {
  return Zod$1(schema, defaultValue);
}

export {
  createServer ,
  createTransport ,
  createStringSchema ,
  createBooleanSchema ,
  createNumberSchema ,
  createOptionalSchema ,
  createDefaultSchema ,
}
/* zod Not a pure module */
