name: Build, Test & Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript type checking
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Run linting (if available)
      run: npm run lint || echo "No lint script found, skipping..."
      continue-on-error: true

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Check for changes since last release
      id: changes
      run: |
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$LATEST_TAG" ]; then
          echo "No previous tags found, proceeding with publish"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          # Check if there are changes since the last tag (excluding docs and CI files)
          CHANGES=$(git diff --name-only $LATEST_TAG..HEAD -- . ':!.github' ':!README.md' ':!*.md' ':!CHANGELOG.md' ':!LICENSE' || echo "changes")
          if [ -n "$CHANGES" ]; then
            echo "Changes detected since $LATEST_TAG:"
            echo "$CHANGES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No significant changes since $LATEST_TAG"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
        fi
        
    - name: Determine version bump type
      id: version_bump
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        # Check commit messages for version bump hints
        COMMITS=$(git log --oneline $(git describe --tags --abbrev=0 2>/dev/null || echo "")..HEAD 2>/dev/null || git log --oneline -10)
        echo "Recent commits:"
        echo "$COMMITS"
        
        if echo "$COMMITS" | grep -qE "(BREAKING CHANGE|BREAKING:|major:)"; then
          echo "bump_type=major" >> $GITHUB_OUTPUT
          echo "Detected major version bump"
        elif echo "$COMMITS" | grep -qE "(feat:|feature:|minor:)"; then
          echo "bump_type=minor" >> $GITHUB_OUTPUT
          echo "Detected minor version bump"
        else
          echo "bump_type=patch" >> $GITHUB_OUTPUT
          echo "Detected patch version bump"
        fi
        
    - name: Calculate new version
      id: new_version
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        BUMP_TYPE=${{ steps.version_bump.outputs.bump_type }}
        echo "Current version: $CURRENT_VERSION"
        echo "Bump type: $BUMP_TYPE"
        
        # Calculate new version without modifying files yet
        IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
        
        case $BUMP_TYPE in
          major)
            NEW_VERSION="$((major + 1)).0.0"
            ;;
          minor)
            NEW_VERSION="$major.$((minor + 1)).0"
            ;;
          patch)
            NEW_VERSION="$major.$minor.$((patch + 1))"
            ;;
        esac
        
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "Calculated new version: $NEW_VERSION"
        
    - name: Update package.json version
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        NEW_VERSION=${{ steps.new_version.outputs.new_version }}
        echo "Updating package.json to version $NEW_VERSION"
        
        # Update version in package.json without creating git commit/tag
        npm version $NEW_VERSION --no-git-tag-version
        
        # Verify the version was updated correctly
        UPDATED_VERSION=$(node -p "require('./package.json').version")
        echo "Verified package.json version: $UPDATED_VERSION"
        
    - name: Build project with new version
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        echo "Building project with new version..."
        npm run build
        
    - name: Run tests with new version
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        echo "Running tests with new version..."
        npm test
        
    - name: Publish to npm
      id: npm_publish
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        NEW_VERSION=${{ steps.new_version.outputs.new_version }}
        echo "Publishing version $NEW_VERSION to npm..."
        
        # Publish to npm - this is the critical step that must succeed
        npm publish
        
        echo "Successfully published version $NEW_VERSION to npm"
        echo "publish_success=true" >> $GITHUB_OUTPUT
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Commit version bump and create tag
      if: steps.changes.outputs.has_changes == 'true' && steps.npm_publish.outputs.publish_success == 'true'
      run: |
        NEW_VERSION=${{ steps.new_version.outputs.new_version }}
        echo "Committing version bump and creating tag for v$NEW_VERSION"
        
        # Only commit and tag after successful npm publish
        git add package.json package-lock.json
        git commit -m "chore: bump version to v$NEW_VERSION [skip ci]"
        git tag "v$NEW_VERSION"
        git push origin HEAD --tags
        
        echo "Successfully committed version bump and created tag v$NEW_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create GitHub Release
      if: steps.changes.outputs.has_changes == 'true' && steps.npm_publish.outputs.publish_success == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.new_version.outputs.new_version }}
        name: Release v${{ steps.new_version.outputs.new_version }}
        body: |
          ## Changes in v${{ steps.new_version.outputs.new_version }}
          
          This release was automatically generated from the latest commits.
          
          ### Version Bump Type: ${{ steps.version_bump.outputs.bump_type }}
          
          ### Recent Commits:
          ```
          ${{ github.event.head_commit.message }}
          ```
          
          ### Installation:
          ```bash
          npm install -g jsx-prop-lookup-mcp-server@${{ steps.new_version.outputs.new_version }}
          ```
          
          For detailed changes, see the [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.new_version.outputs.new_version }}).
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Rollback on failure
      if: failure() && steps.changes.outputs.has_changes == 'true'
      run: |
        echo "Workflow failed, performing rollback..."
        
        # Reset package.json to original version if it was modified
        git checkout HEAD -- package.json package-lock.json || true
        
        # Clean up any local changes
        git reset --hard HEAD || true
        
        echo "Rollback completed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}